-- VividPhantom: Tritanopia-safe colorscheme
-- Based on cyberdream's aesthetic with daltonized palette for blue-yellow color blindness

local p = {
  bg = "#16181a",
  bg_alt = "#1e2124",
  bg_highlight = "#3c4048",
  fg = "#ffffff",
  grey = "#8b949e",
  blue = "#a78bfa",
  green = "#4ade80",
  cyan = "#5eead4",
  red = "#ff6e5e",
  yellow = "#fbbf24",
  magenta = "#ff5ef1",
  pink = "#ff5ea0",
  orange = "#fb923c",
  purple = "#e879f9",
}
p.bg_solid = p.bg
p.bg = "NONE"
p.bg_alt = "NONE"

local function blend(c1, c2, w)
  if c1 == "NONE" or c2 == "NONE" then
    return "NONE"
  end
  local r1, g1, b1 = tonumber(c1:sub(2, 3), 16), tonumber(c1:sub(4, 5), 16), tonumber(c1:sub(6, 7), 16)
  local r2, g2, b2 = tonumber(c2:sub(2, 3), 16), tonumber(c2:sub(4, 5), 16), tonumber(c2:sub(6, 7), 16)
  return string.format("#%02x%02x%02x", math.floor(r1 * w + r2 * (1 - w)), math.floor(g1 * w + g2 * (1 - w)), math.floor(b1 * w + b2 * (1 - w)))
end

vim.cmd("hi clear")
if vim.g.colors_name then
  vim.g.colors_name = nil
end
vim.o.termguicolors = true
vim.g.colors_name = "vividphantom"

vim.opt.fillchars:append({
  horiz = " ", horizup = " ", horizdown = " ",
  vert = " ", vertleft = " ", vertright = " ", verthoriz = " ",
  eob = " ",
})

vim.g.terminal_color_0 = p.bg
vim.g.terminal_color_8 = p.bg_alt
vim.g.terminal_color_7 = p.fg
vim.g.terminal_color_15 = p.grey
vim.g.terminal_color_1 = p.red
vim.g.terminal_color_9 = p.red
vim.g.terminal_color_2 = p.green
vim.g.terminal_color_10 = p.green
vim.g.terminal_color_3 = p.yellow
vim.g.terminal_color_11 = p.yellow
vim.g.terminal_color_4 = p.blue
vim.g.terminal_color_12 = p.blue
vim.g.terminal_color_5 = p.purple
vim.g.terminal_color_13 = p.purple
vim.g.terminal_color_6 = p.cyan
vim.g.terminal_color_14 = p.cyan

local hls = {
  -- Base
  Comment = { fg = p.grey, italic = true },
  ColorColumn = { bg = p.bg_highlight },
  Conceal = { fg = p.grey },
  Cursor = { fg = p.bg, bg = p.fg },
  CursorColumn = { bg = p.bg_highlight },
  CursorLine = { bg = p.bg_highlight },
  Directory = { fg = p.blue },
  DiffAdd = { bg = blend(p.bg_solid, p.green, 0.8) },
  DiffChange = { bg = blend(p.bg_solid, p.blue, 0.8) },
  DiffDelete = { bg = blend(p.bg_solid, p.red, 0.8) },
  DiffText = { bg = blend(p.bg_solid, p.orange, 0.8) },
  Added = { fg = p.green },
  Removed = { fg = p.red },
  EndOfBuffer = { fg = blend(p.bg_highlight, p.fg, 0.9) },
  ErrorMsg = { fg = p.red },
  VertSplit = { fg = p.bg_highlight, bg = p.bg },
  WinSeparator = { fg = p.bg_highlight, bg = p.bg },
  Folded = { fg = p.grey, bg = p.bg },
  FoldColumn = { fg = p.grey, bg = p.bg },
  SignColumn = { fg = p.grey, bg = p.bg },
  Substitute = { fg = p.red, bg = p.bg_highlight },
  LineNr = { fg = blend(p.bg_highlight, p.fg, 0.9) },
  CursorLineNr = { fg = p.grey },
  MatchParen = { fg = p.pink, bg = p.bg_highlight },
  ModeMsg = { fg = p.fg },
  MsgArea = { fg = p.fg },
  MoreMsg = { fg = p.blue },
  NonText = { fg = blend(p.bg_solid, p.grey, 0.55) },
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.bg },
  FloatTitle = { fg = p.cyan, bg = p.bg },
  FloatBorder = { fg = p.bg_highlight, bg = p.bg },
  Pmenu = { fg = p.fg, bg = p.bg },
  PmenuSel = { fg = p.fg, bg = p.bg_highlight },
  PmenuSbar = { fg = p.bg, bg = p.bg_highlight },
  PmenuThumb = { fg = p.bg, bg = p.bg_highlight },
  PmenuMatch = { fg = p.cyan, bg = p.bg_highlight },
  PmenuMatchSel = { fg = p.cyan, bg = p.bg_highlight },
  Question = { fg = p.yellow },
  QuickFixLine = { bg = p.bg_highlight },
  Search = { fg = p.bg_alt, bg = p.fg },
  IncSearch = { fg = p.bg_alt, bg = p.cyan },
  CurSearch = { fg = p.bg_alt, bg = p.cyan },
  SpecialKey = { fg = p.grey },
  SpellBad = { sp = p.red, undercurl = true },
  SpellCap = { sp = p.yellow, undercurl = true },
  SpellLocal = { sp = p.blue, undercurl = true },
  SpellRare = { sp = p.purple, undercurl = true },
  StatusLine = { fg = p.fg, bg = p.bg },
  StatusLineNC = { fg = p.grey, bg = p.bg },
  TabLine = { fg = p.grey, bg = p.bg },
  TabLineFill = { fg = p.grey, bg = p.bg },
  TabLineSel = { fg = p.fg, bg = p.bg_highlight },
  WinBar = { fg = p.fg, bg = p.bg },
  WinBarNC = { fg = p.grey, bg = p.bg },
  Title = { fg = p.fg },
  Visual = { bg = p.bg_highlight },
  VisualNOS = { bg = p.bg_highlight },
  WarningMsg = { fg = p.orange },
  Whitespace = { fg = p.bg_highlight },
  WildMenu = { fg = p.bg, bg = p.blue },

  -- Syntax
  Constant = { fg = p.pink },
  String = { fg = p.green },
  Character = { fg = p.green },
  Boolean = { fg = p.cyan },
  Number = { fg = p.orange },
  Identifier = { fg = p.fg },
  Function = { fg = p.blue },
  Statement = { fg = p.magenta },
  Operator = { fg = p.purple },
  Keyword = { fg = p.orange },
  PreProc = { fg = p.cyan },
  Label = { fg = p.orange },
  Type = { fg = p.purple },
  Special = { fg = p.pink },
  Delimiter = { fg = p.fg },
  Debug = { fg = p.orange },
  Underlined = { underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Error = { fg = p.red },
  Todo = { fg = p.purple, bold = true },

  -- Quickfix
  qfLineNr = { fg = p.grey },
  qfFileName = { fg = p.blue },

  -- HTML/Markdown
  htmlH1 = { fg = p.orange, bold = true },
  htmlH2 = { fg = p.orange, bold = true },
  mkdCodeDelimiter = { fg = p.grey },
  mkdCodeStart = { fg = p.blue },
  mkdCodeEnd = { fg = p.blue },
  markdownHeadingDelimiter = { fg = p.grey },
  markdownCode = { fg = p.cyan },
  markdownCodeBlock = { fg = p.cyan },
  markdownH1 = { fg = p.orange, bold = true },
  markdownH2 = { fg = p.cyan, bold = true },
  markdownH3 = { fg = p.blue, bold = true },
  markdownH4 = { fg = p.purple, bold = true },
  markdownH5 = { fg = p.magenta, bold = true },
  markdownH6 = { fg = p.green, bold = true },
  markdownLinkText = { fg = p.blue, underline = true },

  -- LSP
  LspReferenceText = { bg = p.bg_highlight },
  LspReferenceRead = { bg = p.bg_highlight },
  LspReferenceWrite = { bg = p.bg_highlight },
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.yellow },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan },
  DiagnosticUnnecessary = { fg = p.grey },
  DiagnosticVirtualTextError = { fg = p.red },
  DiagnosticVirtualTextWarn = { fg = p.yellow },
  DiagnosticVirtualTextInfo = { fg = p.blue },
  DiagnosticVirtualTextHint = { fg = p.cyan },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.cyan },
  LspSignatureActiveParameter = { fg = p.orange },
  LspCodeLens = { fg = p.grey },
  LspInlayHint = { fg = p.grey },

  -- Treesitter
  ["@annotation"] = { link = "PreProc" },
  ["@attribute"] = { link = "PreProc" },
  ["@boolean"] = { link = "Boolean" },
  ["@character"] = { link = "Character" },
  ["@character.special"] = { link = "SpecialChar" },
  ["@comment"] = { link = "Comment" },
  ["@conditional"] = { link = "Conditional" },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { link = "Special" },
  ["@constant.macro"] = { link = "Define" },
  ["@constructor"] = { link = "Special" },
  ["@debug"] = { link = "Debug" },
  ["@define"] = { link = "Define" },
  ["@exception"] = { link = "Exception" },
  ["@field"] = { link = "Identifier" },
  ["@float"] = { link = "Float" },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { link = "Function" },
  ["@function.call"] = { link = "@function" },
  ["@function.macro"] = { link = "Macro" },
  ["@include"] = { link = "Include" },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.coroutine"] = { link = "@keyword" },
  ["@keyword.function"] = { link = "Keyword" },
  ["@keyword.operator"] = { link = "@operator" },
  ["@keyword.return"] = { link = "@keyword" },
  ["@keyword.type"] = { fg = p.orange, italic = true },
  ["@label"] = { link = "Label" },
  ["@markup.heading.1"] = { link = "markdownH1" },
  ["@markup.heading.2"] = { link = "markdownH2" },
  ["@markup.heading.3"] = { link = "markdownH3" },
  ["@markup.heading.4"] = { link = "markdownH4" },
  ["@markup.heading.5"] = { link = "markdownH5" },
  ["@markup.heading.6"] = { link = "markdownH6" },
  ["@markup.italic"] = { fg = p.blue, italic = true },
  ["@markup.link.label"] = { link = "Label" },
  ["@markup.link.label.markdown_inline"] = { fg = p.cyan },
  ["@markup.link.markdown_inline"] = { fg = p.blue },
  ["@markup.link.url"] = { fg = p.blue, underline = true },
  ["@markup.list.checked"] = { fg = p.green, bold = true },
  ["@markup.list.unchecked"] = { fg = p.magenta, bold = true },
  ["@markup.quote"] = { link = "Comment" },
  ["@markup.strong"] = { fg = p.pink, bold = true },
  ["@method"] = { link = "Function" },
  ["@method.call"] = { link = "@method" },
  ["@module"] = { fg = p.magenta },
  ["@namespace"] = { link = "Include" },
  ["@none"] = { default = true },
  ["@number"] = { link = "Number" },
  ["@operator"] = { link = "Operator" },
  ["@parameter"] = { link = "Identifier" },
  ["@preproc"] = { link = "PreProc" },
  ["@property"] = { link = "Identifier" },
  ["@punctuation.bracket"] = { link = "Delimiter" },
  ["@punctuation.delimiter"] = { link = "Delimiter" },
  ["@punctuation.special"] = { link = "Delimiter" },
  ["@repeat"] = { link = "Repeat" },
  ["@storageclass"] = { link = "StorageClass" },
  ["@string"] = { link = "String" },
  ["@string.documentation"] = { link = "Comment" },
  ["@string.escape"] = { link = "SpecialChar" },
  ["@string.regex"] = { link = "String" },
  ["@string.special"] = { link = "SpecialChar" },
  ["@symbol"] = { link = "Identifier" },
  ["@tag"] = { link = "Label" },
  ["@tag.attribute"] = { link = "@property" },
  ["@tag.delimiter"] = { link = "Delimiter" },
  ["@text"] = { link = "@none" },
  ["@text.danger"] = { link = "WarningMsg" },
  ["@text.emphasis"] = { italic = true },
  ["@text.environment"] = { link = "Macro" },
  ["@text.environment.name"] = { link = "Type" },
  ["@text.literal"] = { link = "String" },
  ["@text.math"] = { link = "Special" },
  ["@text.note"] = { link = "SpecialComment" },
  ["@text.reference"] = { link = "Constant" },
  ["@text.strike"] = { strikethrough = true },
  ["@text.strong"] = { bold = true, default = true },
  ["@text.title"] = { link = "markdownH1" },
  ["@text.title.2"] = { link = "markdownH2" },
  ["@text.title.3"] = { link = "markdownH3" },
  ["@text.title.4"] = { link = "markdownH4" },
  ["@text.title.5"] = { link = "markdownH5" },
  ["@text.todo"] = { link = "Todo" },
  ["@text.underline"] = { underline = true },
  ["@text.uri"] = { link = "Underlined" },
  ["@text.warning"] = { link = "Todo" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = blend(p.purple, p.pink, 0.65) },
  ["@type.definition"] = { link = "Typedef" },
  ["@type.qualifier"] = { link = "@keyword" },
  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { link = "Special" },

  -- Telescope
  TelescopeBorder = { fg = p.bg_alt, bg = p.bg_alt },
  TelescopeNormal = { bg = p.bg_alt },
  TelescopePreviewBorder = { fg = p.bg_alt, bg = p.bg_alt },
  TelescopePreviewNormal = { bg = p.bg_alt },
  TelescopePreviewTitle = { fg = p.bg_alt, bg = p.green, bold = true },
  TelescopeResultsBorder = { fg = p.bg_alt, bg = p.bg_alt },
  TelescopeResultsNormal = { bg = p.bg_alt },
  TelescopePromptPrefix = { fg = p.blue, bg = p.bg_alt },
  TelescopePromptCounter = { fg = p.cyan, bg = p.bg_alt },
  TelescopePromptTitle = { fg = p.bg_alt, bg = p.blue, bold = true },
  TelescopeResultsTitle = { fg = p.blue, bg = p.bg_alt, bold = true },
  TelescopeSelection = { bg = p.bg_highlight },
  TelescopeMatching = { fg = p.cyan },

  -- cmp
  CmpDocumentation = { fg = p.grey },
  CmpDocumentationBorder = { fg = p.grey },
  CmpGhostText = { fg = p.grey },
  CmpItemAbbr = { fg = p.fg },
  CmpItemAbbrDeprecated = { fg = p.grey, strikethrough = true },
  CmpItemAbbrMatch = { fg = p.purple },
  CmpItemAbbrMatchFuzzy = { fg = p.purple },
  CmpItemKindVariable = { fg = p.cyan },
  CmpItemKindInterface = { fg = p.cyan },
  CmpItemKindText = { fg = p.cyan },
  CmpItemKindFunction = { fg = p.pink },
  CmpItemKindMethod = { fg = p.pink },
  CmpItemKindKeyword = { fg = p.fg },
  CmpItemKindProperty = { fg = p.fg },
  CmpItemKindUnit = { fg = p.fg },
  CmpItemMenu = { fg = p.grey },
  CmpItemKindDefault = { fg = p.grey },

  -- blink.cmp
  BlinkCmpMenuBorder = { fg = blend(p.bg_highlight, p.grey, 0.7) },
  BlinkCmpMenuSelection = { bg = p.bg_highlight },
  BlinkCmpLabel = { fg = p.fg },
  BlinkCmpLabelDeprecated = { fg = p.grey, strikethrough = true },
  BlinkCmpLabelMatch = { fg = p.cyan },
  BlinkCmpSignatureHelpActiveParameter = { fg = p.cyan },
  BlinkCmpKindText = { fg = p.green },
  BlinkCmpKindMethod = { fg = p.blue },
  BlinkCmpKindFunction = { fg = p.blue },
  BlinkCmpKindConstructor = { fg = p.purple },
  BlinkCmpKindField = { fg = p.green },
  BlinkCmpKindVariable = { fg = p.orange },
  BlinkCmpKindProperty = { fg = p.red },
  BlinkCmpKindClass = { fg = p.blue },
  BlinkCmpKindInterface = { fg = p.blue },
  BlinkCmpKindStruct = { fg = p.blue },
  BlinkCmpKindModule = { fg = p.blue },
  BlinkCmpKindUnit = { fg = p.orange },
  BlinkCmpKindValue = { fg = p.orange },
  BlinkCmpKindEnum = { fg = p.orange },
  BlinkCmpKindEnumMember = { fg = p.orange },
  BlinkCmpKindKeyword = { fg = p.magenta },
  BlinkCmpKindConstant = { fg = p.pink },
  BlinkCmpKindSnippet = { fg = p.green },
  BlinkCmpKindColor = { fg = p.green },
  BlinkCmpKindFile = { fg = p.green },
  BlinkCmpKindReference = { fg = p.green },
  BlinkCmpKindFolder = { fg = p.green },
  BlinkCmpKindEvent = { fg = p.green },
  BlinkCmpKindOperator = { fg = p.magenta },
  BlinkCmpKindTypeParameter = { fg = p.pink },

  -- Gitsigns
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.orange },
  GitSignsDelete = { fg = p.red },
  GitSignsAddInline = { bg = blend(p.bg_solid, p.green, 0.9) },
  GitSignsChangeInline = { bg = blend(p.bg_solid, p.blue, 0.9) },
  GitSignsDeleteInline = { bg = blend(p.bg_solid, p.red, 0.9) },

  -- Lazy
  LazyH1 = { fg = p.blue, bold = true },
  LazyH2 = { fg = p.fg, bold = true },
  LazyButton = { fg = p.fg, bg = p.bg_highlight },
  LazyButtonActive = { fg = p.fg, bg = p.bg_highlight, bold = true },
  LazyProgressDone = { bold = true, fg = p.magenta },
  LazyProgressTodo = { bold = true, fg = p.grey },
  LazyReasonCmd = { fg = p.yellow },
  LazyReasonEvent = { fg = p.magenta },
  LazyReasonKeys = { fg = p.cyan },
  LazyReasonPlugin = { fg = p.green },
  LazyReasonRequire = { fg = p.orange },
  LazyReasonRuntime = { fg = p.red },
  LazyReasonStart = { fg = p.blue },
  LazySpecial = { fg = p.cyan },

  -- Notify
  NotifyERRORIcon = { fg = p.red },
  NotifyERRORTitle = { fg = p.pink },
  NotifyERRORBorder = { fg = p.bg_highlight },
  NotifyERRORBody = { fg = p.fg },
  NotifyINFOIcon = { fg = p.green },
  NotifyINFOTitle = { fg = p.cyan },
  NotifyINFOBorder = { fg = p.bg_highlight },
  NotifyINFOBody = { fg = p.fg },
  NotifyWARNIcon = { fg = p.orange },
  NotifyWARNTitle = { fg = p.yellow },
  NotifyWARNBorder = { fg = p.bg_highlight },
  NotifyWARNBody = { fg = p.fg },
  NotifyTRACEIcon = { fg = p.purple },
  NotifyTRACETitle = { fg = p.magenta },
  NotifyTRACEBorder = { fg = p.bg_highlight },
  NotifyDEBUGIcon = { fg = p.grey },
  NotifyDEBUGTitle = { fg = p.grey },
  NotifyDEBUGBorder = { fg = p.bg_highlight },
  NotifyDEBUGBody = { fg = p.fg },
  NotifyBackground = { bg = "NONE" },

  -- Noice
  NoiceFormatProgressDone = { fg = p.bg_alt, bg = p.cyan },
  NoiceFormatProgressTodo = { fg = p.grey, bg = p.bg_highlight },
  NoiceLspProgressClient = { fg = p.blue },
  NoiceLspProgressSpinner = { fg = p.orange },
  NoiceLspProgressTitle = { fg = p.cyan },

  -- Snacks
  SnacksNotifierIconError = { fg = p.red },
  SnacksNotifierTitleError = { fg = p.red },
  SnacksNotifierIconInfo = { fg = p.blue },
  SnacksNotifierTitleInfo = { fg = p.blue },
  SnacksNotifierIconTrace = { fg = p.purple },
  SnacksNotifierTitleTrace = { fg = p.purple },
  SnacksNotifierIconWarn = { fg = p.yellow },
  SnacksNotifierTitleWarn = { fg = p.yellow },
  SnacksNotifierBorderDebug = { fg = p.bg_highlight },
  SnacksDashboardDesc = { fg = p.cyan },
  SnacksDashboardFile = { fg = p.cyan },
  SnacksDashboardDir = { fg = p.grey },
  SnacksDashboardHeader = { fg = blend(p.purple, p.fg, 0.3) },
  SnacksDashboardIcon = { fg = p.blue },
  SnacksDashboardKey = { fg = p.orange },
  SnacksPickerMatch = { fg = p.cyan },
  SnacksPickerTotals = { fg = p.cyan, bold = true },
  SnacksPickerPrompt = { fg = p.blue, bold = true },
  SnacksPickerBorder = { fg = p.bg_alt, bg = p.bg_alt },
  SnacksPickerNormal = { bg = p.bg_alt },
  SnacksPickerBox = { bg = p.bg_alt },
  SnacksPickerList = { bg = p.bg_alt },
  SnacksPickerInput = { bg = p.bg_alt },
  SnacksPickerPreview = { bg = p.bg_alt },
  SnacksPickerBoxTitle = { fg = p.bg_solid, bg = p.blue },
  SnacksPickerPreviewTitle = { fg = p.bg_solid, bg = p.green },
  SnacksPickerListTitle = { fg = p.bg_solid, bg = p.magenta },
  SnacksPickerInputTitle = { fg = p.bg_solid, bg = p.cyan },

  -- WhichKey
  WhichKey = { fg = p.cyan },
  WhichKeyGroup = { fg = p.blue },
  WhichKeyDesc = { fg = p.pink },
  WhichKeySeperator = { fg = p.grey },
  WhichKeyFloat = { bg = p.bg },
  WhichKeyValue = { fg = p.blue },
  WhichKeyIcon = { fg = p.blue },
  WhichKeyIconBlue = { fg = p.blue },
  WhichKeyIconCyan = { fg = p.cyan },
  WhichKeyIconGreen = { fg = p.green },
  WhichKeyIconGrey = { fg = p.grey },
  WhichKeyIconOrange = { fg = p.orange },
  WhichKeyIconPurple = { fg = p.purple },
  WhichKeyIconRed = { fg = p.red },
  WhichKeyIconYellow = { fg = p.yellow },

  -- Trouble
  TroubleCode = { fg = p.magenta },
  TroubleCount = { bg = p.bg_highlight, bold = true },
  TroubleDirectory = { fg = p.grey, bold = true },
  TroubleFilename = { fg = p.cyan },
  TroubleIconArray = { fg = p.pink },
  TroubleIconDirectory = { fg = p.blue },

  -- IndentBlankline
  IblIndent = { fg = p.bg_highlight },
  IblScope = { fg = p.grey },

  -- Rainbow delimiters
  RainbowDelimiterRed = { fg = p.red },
  RainbowDelimiterYellow = { fg = p.yellow },
  RainbowDelimiterBlue = { fg = p.blue },
  RainbowDelimiterOrange = { fg = p.orange },
  RainbowDelimiterGreen = { fg = p.green },
  RainbowDelimiterViolet = { fg = p.purple },
  RainbowDelimiterCyan = { fg = p.cyan },

  -- Mini
  MiniClueNextKey = { fg = p.green },
  MiniDepsChangeAdded = { fg = p.green },
  MiniDepsChangeRemoved = { fg = p.red },
  MiniDiffOverAdd = { bg = blend(p.bg_solid, p.green, 0.8) },
  MiniDiffOverChange = { bg = blend(p.bg_solid, p.blue, 0.8) },
  MiniDiffOverContext = { bg = blend(p.bg_solid, p.orange, 0.8) },
  MiniDiffOverDelete = { bg = blend(p.bg_solid, p.red, 0.8) },
  MiniDiffSignAdd = { fg = p.green },
  MiniDiffSignChange = { fg = p.orange },
  MiniDiffSignDelete = { fg = p.red },
  MiniFilesBorder = { fg = p.bg_highlight },
  MiniFilesBorderModified = { fg = p.pink },
  MiniFilesDirectory = { fg = p.blue },
  MiniFilesTitle = { fg = blend(p.bg_highlight, p.cyan, 0.7) },
  MiniFilesTitleFocused = { fg = p.cyan },
  MiniHipatternsFixme = { fg = p.bg_solid, bg = p.red, bold = true },
  MiniHipatternsHack = { fg = p.bg_solid, bg = p.yellow, bold = true },
  MiniHipatternsNote = { fg = p.bg_solid, bg = p.blue, bold = true },
  MiniHipatternsTodo = { fg = p.bg_solid, bg = p.cyan, bold = true },
  MiniIconsBlue = { fg = p.blue },
  MiniIconsCyan = { fg = p.cyan },
  MiniIconsGreen = { fg = p.green },
  MiniIconsOrange = { fg = p.orange },
  MiniIconsPurple = { fg = p.purple },
  MiniIconsRed = { fg = p.red },
  MiniIconsYellow = { fg = p.yellow },
  MiniIndentscopeSymbol = { fg = p.grey },
  MiniJump2dDim = { fg = p.grey },
  MiniJump2dSpot = { fg = p.orange, bold = true, nocombine = true },
  MiniJump2dSpotAhead = { fg = p.cyan, bg = p.bg, nocombine = true },
  MiniJump2dSpotUnique = { fg = p.yellow, bold = true, nocombine = true },
  MiniPickMatchMarked = { bg = p.bg_highlight },
  MiniPickMatchRanges = { fg = p.orange },
  MiniStarterHeader = { fg = p.cyan },
  MiniStarterSection = { fg = p.blue },
  MiniStatuslineModeCommand = { fg = p.bg_solid, bg = p.yellow, bold = true },
  MiniStatuslineModeInsert = { fg = p.bg_solid, bg = p.green, bold = true },
  MiniStatuslineModeNormal = { fg = p.bg_solid, bg = p.blue, bold = true },
  MiniStatuslineModeOther = { fg = p.bg_solid, bg = p.cyan, bold = true },
  MiniStatuslineModeReplace = { fg = p.bg_solid, bg = p.red, bold = true },
  MiniStatuslineModeVisual = { fg = p.bg_solid, bg = p.magenta, bold = true },
  MiniTablineCurrent = { fg = p.fg, bg = p.bg_highlight, bold = true },
  MiniTablineHidden = { fg = p.grey, bg = p.bg },
  MiniTablineVisible = { fg = p.fg, bg = p.bg_highlight },
  MiniTestFail = { fg = p.red, bold = true },
  MiniTestPass = { fg = p.green, bold = true },
  MiniTrailspace = { bg = p.red },

  -- Render Markdown
  RenderMarkdownH1 = { fg = p.orange, bold = true },
  RenderMarkdownH2 = { fg = p.cyan, bold = true },
  RenderMarkdownH3 = { fg = p.blue, bold = true },
  RenderMarkdownH4 = { fg = p.purple, bold = true },
  RenderMarkdownH5 = { fg = p.magenta, bold = true },
  RenderMarkdownH6 = { fg = p.green, bold = true },
  RenderMarkdownH1Bg = { bg = blend(p.bg_solid, p.orange, 0.85) },
  RenderMarkdownH2Bg = { bg = blend(p.bg_solid, p.cyan, 0.85) },
  RenderMarkdownH3Bg = { bg = blend(p.bg_solid, p.blue, 0.85) },
  RenderMarkdownH4Bg = { bg = blend(p.bg_solid, p.purple, 0.85) },
  RenderMarkdownH5Bg = { bg = blend(p.bg_solid, p.magenta, 0.85) },
  RenderMarkdownH6Bg = { bg = blend(p.bg_solid, p.green, 0.85) },
  RenderMarkdownQuote = { fg = p.grey },
  RenderMarkdownCode = { bg = p.bg_alt },
  RenderMarkdownBullet = { fg = p.grey },
  RenderMarkdownDash = { fg = p.grey },
  RenderMarkdownTodo = { fg = p.orange },
  RenderMarkdownTableHead = { fg = p.grey },
  RenderMarkdownSuccess = { fg = p.green },
  RenderMarkdownInfo = { fg = p.blue },
  RenderMarkdownHint = { fg = p.cyan },
  RenderMarkdownWarn = { fg = p.orange },
  RenderMarkdownError = { fg = p.red },

  -- Treesitter context
  TreesitterContext = { bg = blend(p.bg, p.bg_highlight, 0.7) },
  TreesitterContextLineNumber = { fg = blend(p.grey, p.bg_highlight, 0.8) },
}

for group, attrs in pairs(hls) do
  vim.api.nvim_set_hl(0, group, attrs)
end
